# This is a basic workflow to help you get started with Actions

name: Dependencies

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: Marcisbee/dependency-check-action@1.0.1
        with:
          PATH: "/src"
